//  各方法连接端点集
export enum Endpoints {
  /** 公告 */
  Announcement = 'announcement',
  /** 紧急公告 */
  AnnouncementUrgent = 'announcement/urgent',
  /** API密钥 */
  APIKey = 'apiKey',
  /** 禁用API密钥 */
  APIKeyDisable = 'apiKey/disable',
  /** 启用API密钥 */
  APIKeyEnable = 'apiKey/enable',
  /** Trollbox聊天室 */
  Chat = 'chat',
  /** Trollbox聊天室频道 */
  ChatChannels = 'chat/channels',
  /** Trollbox聊天室频道连接人数（用户、机器人） */
  ChatConnected = 'chat/connected',
  /** 获取全部原始的执行交易 */
  Execution = 'execution',
  /** 获取所有影响余额的执行。 这包括每笔交易，保险费用和结算。 */
  ExecutionTradeHistory = 'execution/tradeHistory',
  /** 资金费率记录 */
  Funding = 'funding',
  /** 商品(可交易合约、指数和历史) */
  Instrument = 'instrument',
  /** 在24小时内获取所有过期的商品 */
  InstrumentActive = 'instrument/active',
  /** 帮助类方法。 获取所有可用商品和所有指数。 */
  /** 这是instrument/indices和instrument/active的结合。 */
  InstrumentActiveAndIndices = 'instrument/activeAndIndices',
  /** 返回所有可用的合约系列和区间对。 */
  InstrumentActiveIntervals = 'instrument/activeIntervals',
  /** 综合指数。 */
  InstrumentCompositeIndex = 'instrument/compositeIndex',
  /** 价格指数。 */
  InstrumentIndices = 'instrument/indices',
  /** 获取保险基金的历史。 */
  Insurance = 'insurance',
  /** 排行榜（盈利以及回报率） */
  Leaderboard = 'leaderboard',
  /** 在排行榜上获取你的别名。 */
  LeaderboardName = 'leaderboard/name',
  /** 强制平仓 */
  Liquidation = 'liquidation',
  /** 当前通知 */
  Notification = 'notification',
  /** 订单 */
  Order = 'order',
  /** 取消全部订单 */
  OrderAll = 'order/all',
  /** 创建多条相同商品的订单 */
  OrderBulk = 'order/bulk',
  /** 在指定的超时后自动取消您的所有订单。 */
  OrderCancelAllAfter = 'order/cancelAllAfter',
  /** 平仓 */
  OrderClosePosition = 'order/closePosition',
  /** 完整的 level 2 委托列表 */
  OrderBookL2 = 'orderBook/L2',
  /** 头寸 */
  Position = 'position',
  /** 为头寸设置保证金（逐仓或全仓） */
  PositionIsolate = 'position/isolate',
  /** 头寸杠杆 */
  PositionLeverage = 'position/leverage',
  /** 头寸风险限额 */
  PositionRiskLimit = 'position/riskLimit',
  /** 头寸转入保证金 */
  PositionTransferMargin = 'position/transferMargin',
  /** 报价 */
  Quote = 'quote',
  /** 时间范围内报价 */
  QuoteBucketed = 'quote/bucketed',
  /** 获取此API的数据对象的模型结构。 */
  Schema = 'schema',
  /** 返回websocket使用的帮助文本和主题列表。 */
  SchemaWebsocketHelp = 'schema/websocketHelp',
  /** 结算历史 */
  Settlement = 'settlement',
  /** 获取整个交易所和每个系列的营业额和数量统计。 */
  Stats = 'stats',
  /** 获取整个交易所和每个系列的营业额和数量统计的历史。 */
  StatsHistory = 'stats/history',
  /** 获取美元的汇率统计摘要。 */
  StatsHistoryUSD = 'stats/historyUSD',
  /** 交易 */
  Trade = 'trade',
  /** 在时间桶中获取以前的交易。 */
  TradeBucketed = 'trade/bucketed',
  /** 用户 */
  User = 'user',
  // TODO
}
